In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/DATASETS/DateFruit_Dataset.csv")

In [ ]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [ ]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [ ]:
df['Class'].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [ ]:
df.shape

(898, 35)

In [ ]:
X=df.drop('Class',axis=1)
y=df['Class']

In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

In [ ]:
X_train_tensor= torch.tensor(X_train_scaled,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled,dtype=torch.float32)

y_train_tensor = torch.tensor(y_train,dtype=torch.long)
y_test_tensor = torch.tensor(y_test,dtype = torch.long)

In [ ]:
train_dataset = TensorDataset(X_train_tensor,y_train_tensor)
test_dataset = TensorDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32)

In [ ]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.model=nn.Sequential(
        nn.Linear(X.shape[1],64),
        nn.ReLU(),

        nn.Linear(64,64),
        nn.ReLU(),

        nn.Linear(64,7)
    )

  def forward(self,x):
      return self.model(x)

In [ ]:
model = ANN()

criterion = nn.CrossEntropyLoss()
optimiser = optim.Adam(model.parameters())

In [ ]:
epochs = 100

for epoch in range(epochs):
  model.train()
  running_loss = 0.0

  for xb,yb in train_loader:
    optimiser.zero_grad()

    outputs = model(xb)
    loss = criterion(outputs,yb)
    loss.backward()

    optimiser.step()

    running_loss+=loss

  train_loss = running_loss/len(train_loader)

  print(f"for epoch = {epoch+1}/{epochs} training loss = {train_loss}")

for epoch = 1/100 training loss = 0.02395254373550415
for epoch = 2/100 training loss = 0.02211594767868519
for epoch = 3/100 training loss = 0.02441367693245411
for epoch = 4/100 training loss = 0.02321086823940277
for epoch = 5/100 training loss = 0.024335920810699463
for epoch = 6/100 training loss = 0.024838009849190712
for epoch = 7/100 training loss = 0.023004474118351936
for epoch = 8/100 training loss = 0.019924480468034744
for epoch = 9/100 training loss = 0.022055793553590775
for epoch = 10/100 training loss = 0.0197608582675457
for epoch = 11/100 training loss = 0.022518182173371315
for epoch = 12/100 training loss = 0.01785435900092125
for epoch = 13/100 training loss = 0.018335288390517235
for epoch = 14/100 training loss = 0.017483506351709366
for epoch = 15/100 training loss = 0.022698136046528816
for epoch = 16/100 training loss = 0.020224962383508682
for epoch = 17/100 training loss = 0.017418481409549713
for epoch = 18/100 training loss = 0.016706006601452827
for epoch = 19/100 training loss = 0.018360508605837822
for epoch = 20/100 training loss = 0.019531341269612312
for epoch = 21/100 training loss = 0.015736635774374008
for epoch = 22/100 training loss = 0.015626205131411552
for epoch = 23/100 training loss = 0.015077580697834492
for epoch = 24/100 training loss = 0.014223768375813961
for epoch = 25/100 training loss = 0.014827271923422813
for epoch = 26/100 training loss = 0.0135878911241889
for epoch = 27/100 training loss = 0.016168948262929916
for epoch = 28/100 training loss = 0.01571783795952797
for epoch = 29/100 training loss = 0.012543316930532455
for epoch = 30/100 training loss = 0.01583527959883213
for epoch = 31/100 training loss = 0.013877839781343937
for epoch = 32/100 training loss = 0.013260076753795147
for epoch = 33/100 training loss = 0.012674842029809952
for epoch = 34/100 training loss = 0.011402620933949947
for epoch = 35/100 training loss = 0.012144695036113262
for epoch = 36/100 training loss = 0.011019905097782612
for epoch = 37/100 training loss = 0.01123533584177494
for epoch = 38/100 training loss = 0.013635320588946342
for epoch = 39/100 training loss = 0.012077145278453827
for epoch = 40/100 training loss = 0.011899166740477085
for epoch = 41/100 training loss = 0.010988596826791763
for epoch = 42/100 training loss = 0.010213801637291908
for epoch = 43/100 training loss = 0.010226007550954819
for epoch = 44/100 training loss = 0.009815617464482784
for epoch = 45/100 training loss = 0.01560303196310997
for epoch = 46/100 training loss = 0.018768547102808952
for epoch = 47/100 training loss = 0.015980493277311325
for epoch = 48/100 training loss = 0.010356158018112183
for epoch = 49/100 training loss = 0.009141557849943638
for epoch = 50/100 training loss = 0.010276518762111664
for epoch = 51/100 training loss = 0.008915401995182037
for epoch = 52/100 training loss = 0.008469844236969948
for epoch = 53/100 training loss = 0.007729061879217625
for epoch = 54/100 training loss = 0.007322303019464016
for epoch = 55/100 training loss = 0.007124091498553753
for epoch = 56/100 training loss = 0.0070655494928359985
for epoch = 57/100 training loss = 0.009012390859425068
for epoch = 58/100 training loss = 0.010901110246777534
for epoch = 59/100 training loss = 0.009757650084793568
for epoch = 60/100 training loss = 0.009011944755911827
for epoch = 61/100 training loss = 0.01000830065459013
for epoch = 62/100 training loss = 0.006827836390584707
for epoch = 63/100 training loss = 0.00632619671523571
for epoch = 64/100 training loss = 0.006717876996845007
for epoch = 65/100 training loss = 0.0063696084544062614
for epoch = 66/100 training loss = 0.007525497581809759
for epoch = 67/100 training loss = 0.01151981856673956
for epoch = 68/100 training loss = 0.007103360258042812
for epoch = 69/100 training loss = 0.006423013284802437
for epoch = 70/100 training loss = 0.005066526122391224
for epoch = 71/100 training loss = 0.005364689975976944
for epoch = 72/100 training loss = 0.005118596367537975
for epoch = 73/100 training loss = 0.004933137446641922
for epoch = 74/100 training loss = 0.004783194977790117
for epoch = 75/100 training loss = 0.005371070001274347
for epoch = 76/100 training loss = 0.005329762119799852
for epoch = 77/100 training loss = 0.004977033939212561
for epoch = 78/100 training loss = 0.004115315619856119
for epoch = 79/100 training loss = 0.004418347030878067
for epoch = 80/100 training loss = 0.00535617908462882
for epoch = 81/100 training loss = 0.005088446196168661
for epoch = 82/100 training loss = 0.004291648976504803
for epoch = 83/100 training loss = 0.0041189235635101795
for epoch = 84/100 training loss = 0.003785875393077731
for epoch = 85/100 training loss = 0.005345660727471113
for epoch = 86/100 training loss = 0.004935206845402718
for epoch = 87/100 training loss = 0.012317252345383167
for epoch = 88/100 training loss = 0.007807684130966663
for epoch = 89/100 training loss = 0.005385799333453178
for epoch = 90/100 training loss = 0.004930861759930849
for epoch = 91/100 training loss = 0.0063272882252931595
for epoch = 92/100 training loss = 0.005186531692743301
for epoch = 93/100 training loss = 0.003978670109063387
for epoch = 94/100 training loss = 0.0035674150567501783
for epoch = 95/100 training loss = 0.0036073988303542137
for epoch = 96/100 training loss = 0.0034723938442766666
for epoch = 97/100 training loss = 0.0032720649614930153
for epoch = 98/100 training loss = 0.0045050568878650665
for epoch = 99/100 training loss = 0.0032115215435624123
for epoch = 100/100 training loss = 0.0030675504822283983

In [ ]:
model.eval()

total = 0
correct= 0

with torch.no_grad():
  for xb,yb in test_loader:
    outputs=model(xb)
    _,predicted=torch.max(outputs,1)

    correct+=(predicted==yb).sum().item()
    total+=yb.size(0)

print("total =",total)
print("correct= ",correct)

print("accuracy=",correct/total *100)

total = 180
correct=  170
accuracy= 94.44444444444444